

const GREETINGS = [
  {
    id: 'yo',
    recipient: 'Boss',
    sound: 'JINGLE',
    message: "Wishing you and your family a happy, healthy Christmas! Thank you for all your incredible support this year. May your holiday be filled with magical moments and cherished memories. You're the leader who truly inspires us all!",
    confettiColors: ['#1B5E20', '#FFD700', '#0D47A1', '#4A148C', '#B71C1C'],
    niceScore: 98,
    icon: '👑',
  },
  {
    id: 'solleil',
    recipient: 'Miss Solleil',
    sound: 'BELLS',
    message: "Thank you for your incredible kindness and support each month. Your generosity means more than words can say. Wishing you the warmest Christmas filled with joy, peace, and special moments with loved ones.",
    confettiColors: ['#880E4F', '#F57C00', '#004D40', '#D81B60', '#1A237E'],
    niceScore: 97,
    icon: '🤝',
  },
  {
    id: 'kitcha',
    recipient: 'Miss Kitchana',
    sound: 'CHOIR',
    message: "Thank you for leading with kindness, not commands. Your thoughtful guidance and suggestions make all the difference. You're truly the manager of the year! May your Christmas overflow with love and happiness.",
    confettiColors: ['#006064', '#FF6F00', '#33691E', '#01579B', '#311B92'],
    niceScore: 96,
    icon: '⭐',
  },
  {
    id: 'chris',
    recipient: 'Chris',
    sound: 'JINGLE',
    message: "Thank you for being an amazing DevOps! I appreciate how you always assist with CI/CD and server questions. Your expertise makes everything run smoothly. Wishing you a Christmas full of fun and great times!",
    confettiColors: ['#4A148C', '#BF360C', '#FFD700', '#0D47A1', '#1B5E20'],
    niceScore: 94,
    icon: '⚙️',
  },
  {
    id: 'marc',
    recipient: 'Marc',
    sound: 'BELLS',
    message: "Thank you for all the backend assistance! Your help has been invaluable, and I must say – awesome hairstyle too! 😄 Wishing you a truly awesome Christmas with plenty of cheer and celebration!",
    confettiColors: ['#B71C1C', '#4A148C', '#FFD700', '#1B5E20', '#0D47A1'],
    niceScore: 93,
    icon: '💻',
  },
  {
    id: 'sheena',
    recipient: 'Sheena',
    sound: 'CHOIR',
    message: "The best UI/UX expert I've ever worked with! Thank you for always being there to help and for creating such amazing experiences. May your Christmas sparkle with creativity and joy!",
    confettiColors: ['#D81B60', '#F57C00', '#880E4F', '#1A237E', '#004D40'],
    niceScore: 95,
    icon: '🎨',
  },
  {
    id: 'jp',
    recipient: 'JP',
    sound: 'JINGLE',
    message: "To our incredible Tester – thank you for your hard work and for never refusing help! Your dedication ensures everything works perfectly. Forever grateful to spend this Christmas season with you!",
    confettiColors: ['#33691E', '#01579B', '#FF6F00', '#006064', '#311B92'],
    niceScore: 92,
    icon: '🔍',
  },
  {
  id: 'jd',
  recipient: 'JD',
  sound: 'BELLS',
  message: "JD, your work on the real-time chat feature has been truly inspiring! You always find smart solutions, and it motivates the whole team. Wishing you a Christmas filled with joy, rest, and all the things that make you happy!",
  confettiColors: ['#0D47A1', '#FFD700', '#4A148C', '#1B5E20', '#B71C1C'],
  niceScore: 91,
  icon: '💬',
},
{
  id: 'emys',
  recipient: 'Miss Emys',
  sound: 'CHOIR',
  message: "Miss Emys, thank you for your patience, guidance, and the kindness you always show whenever I reach out. You make everyone’s work lighter. May this Christmas bring you peace, joy, and the warmth of God’s blessings!",
  confettiColors: ['#4A148C', '#1B5E20', '#BF360C', '#0D47A1', '#FFD700'],
  niceScore: 96,
  icon: '🙏',
},
{
  id: 'yves',
  recipient: 'Yves',
  sound: 'BELLS',
  message: "Yves, your positivity and steady support have been a huge encouragement this year. I’m grateful for every moment you helped make our days easier. Wishing you a bright, joyful, and meaningful Christmas season!",
  confettiColors: ['#1A237E', '#004D40', '#B71C1C', '#0D47A1', '#FFD700'],
  niceScore: 94,
  icon: '🎄',
},
{
  id: 'nycka',
  recipient: 'Nycka',
  sound: 'CHOIR',
  message: "Nycka, your cheerful energy always brings light to the team! May this Christmas surround you with love, comfort, and the gentle joy of the season. Wishing you the warmest and happiest holidays!",
  confettiColors: ['#880E4F', '#4E342E', '#1A237E', '#00695C', '#F9A825'],
  niceScore: 97,
  icon: '✨',
},
{
  id: 'deniel',
  recipient: 'Sir Deniel',
  sound: 'SANTA',
  message: "Sir Deniel, thank you for leading with clarity, patience, and genuine care. Your guidance has made this year truly meaningful. Wishing you a wonderful and blessed Christmas filled with rest and happiness!",
  confettiColors: ['#880E4F', '#4E342E', '#1A237E', '#00695C', '#F9A825'],
  niceScore: 97,
  icon: '🎄',
},
{
  id: 'xerxizz',
  recipient: 'Xerxizz',
  sound: 'HIGH',
  message: "Hey bro, hope I spelled your name right! 😄 Thanks for the laughs and good vibes this year. Wishing you a fun, joyful, and unforgettable Christmas season!",
  confettiColors: ['#880E4F', '#4E342E', '#1A237E', '#00695C', '#F9A825'],
  niceScore: 97,
  icon: '✨',
}



];

export { GREETINGS };

